name: swift-master
on:
  push:
    paths-ignore: 
      - .github/workflows/playground.yml
      - .github/workflows/swift-master-nsd.yml
      - .github/workflows/swift-5.2.yml
      - README.md

  schedule:
    - cron: '0 22 * * *'

env:
  SW_CURL_VERSION: development
  SW_ICU_VERSION: 64
  SW_XML2_VERSION: development
  SW_ZLIB_VERSION: 1.2.11

jobs:
  icu:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: 'maint/maint-${{ env.SW_ICU_VERSION }}'
          fetch-depth: 1
          path: 'icu'
      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\icu\steps\configure-build-environment.cmd

      - name: Configure ICU
        shell: cmd
        run: scripts\workflows\jobs\icu\steps\configure-icu.cmd

      - name: Build ICU
        shell: cmd
        run: scripts\workflows\jobs\icu\steps\build-icu.cmd

      - name: Install ICU
        shell: cmd
        run: scripts\workflows\jobs\icu\steps\install-icu.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: icu
          path: i

  curl:

    runs-on: windows-latest
    needs: [zlib]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout curl
        uses: actions/checkout@v2
        with:
          repository: 'curl/curl'
          ref: 'master'
          fetch-depth: 1
          path: 'curl'
      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: 'a'
      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\curl\steps\configure-build-environment.cmd

      - name: Configure curl
        shell: cmd
        run: scripts\workflows\jobs\curl\steps\configure-curl.cmd

      - name: Build curl
        shell: cmd
        run: scripts\workflows\jobs\curl\steps\build-curl.cmd

      - name: Install curl
        shell: cmd
        run: scripts\workflows\jobs\curl\steps\install-curl.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: curl
          path: i

  libxml2:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout libxml2
        uses: actions/checkout@v2
        with:
          repository: 'compnerd/libxml2'
          ref: 'cmake'
          fetch-depth: 1
          path: 'libxml2'
      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\libxml2\steps\configure-build-environment.cmd

      - name: Configure libxml2
        shell: cmd
        run: scripts\workflows\jobs\libxml2\steps\configure-libxml2.cmd

      - name: Build libxml2
        shell: cmd
        run: scripts\workflows\jobs\libxml2\steps\build-libxml2.cmd

      - name: Install libxml2
        shell: cmd
        run: scripts\workflows\jobs\libxml2\steps\install-libxml2.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: libxml2
          path: i

  zlib:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: 'madler/zlib'
          ref: 'refs/tags/v${{ env.SW_ZLIB_VERSION }}'
          fetch-depth: 1
          path: 'zlib'
      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\zlib\steps\configure-build-environment.cmd

      - name: Configure zlib
        shell: cmd
        run: scripts\workflows\jobs\zlib\steps\configure-zlib.cmd

      - name: Build zlib
        shell: cmd
        run: scripts\workflows\jobs\zlib\steps\build-zlib.cmd

      - name: Install zlib
        shell: cmd
        run: scripts\workflows\jobs\zlib\steps\install-zlib.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: zlib
          path: i

  toolchain:

    runs-on: windows-latest
    needs: [icu]
    strategy:
      matrix:
        branch: ['master']
        include:
          - branch: 'master'
            llvm-ref: 'swift/master'
            cmark-ref: 'master'
            libdispatch-ref: 'master'
            swift-ref: 'master'
          - branch: '5.2'
            llvm-ref: 'swift/swift-5.2-branch'
            cmark-ref: 'swift-5.2-branch'
            libdispatch-ref: 'swift-5.2-branch'
            swift-ref: 'swift-5.2-branch'

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Configure Git
        shell: cmd
        run: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true

      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: ${{ matrix.llvm-ref }}
          fetch-depth: 1
          path: 's/toolchain' 
      - name: Checkout cmark
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-cmark'
          ref: ${{ matrix.cmark-ref }}
          fetch-depth: 1
          path: 's/toolchain/cmark' 
      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: ${{ matrix.libdispatch-ref }}
          fetch-depth: 1
          path: 's/swift-corelibs-libdispatch' 
      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: ${{ matrix.swift-ref }}
          fetch-depth: 1
          path: 's/toolchain/swift'
      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: 'a'
      - name: Collect Checkout Info
        shell: cmd
        run: |
          mkdir %GITHUB_WORKSPACE%\checkout
          git -C s/toolchain rev-parse HEAD > %GITHUB_WORKSPACE%\checkout\llvm-project.txt
          git -C s/toolchain/cmark rev-parse HEAD > %GITHUB_WORKSPACE%\checkout\swift-cmark.txt
          git -C s/swift-corelibs-libdispatch rev-parse HEAD > %GITHUB_WORKSPACE%\checkout\swift-corelibs-libdispatch.txt
          git -C s/toolchain/swift rev-parse HEAD > %GITHUB_WORKSPACE%\checkout\swift.txt

      - name: Upload Checkout Info
        uses: actions/upload-artifact@v1
        with:
          name: checkout-${{ matrix.branch }}
          path: 'checkout'

      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\configure-build-environment.cmd

      - name: Configure LLVM Build Tools
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\configure-llvm-build-tools.cmd

      - name: Build LLVM Build Tools
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\build-llvm-build-tools.cmd

      - name: Build Clang Build Tools
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\build-clang-build-tools.cmd

      - name: Build LLDB Build Tools
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\build-lldb-build-tools.cmd

      - name: Configure SDK Modules
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\configure-sdk-modules.cmd

      - name: Use Python 2.7.x
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 2.7.x

      - name: Expose Build Tools
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\expose-build-tools.cmd

      - name: Configure Toolchain
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\configure-toolchain.cmd

      - name: Build Toolchain
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\build-toolchain.cmd

      - name: Install Toolchain
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\install-toolchain.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: toolchain-${{ matrix.branch }}
          path: i

      - name: Configure Test Environment
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\configure-test-environment.cmd

      - name: Check Swift
        continue-on-error: true
        shell: cmd
        run: scripts\workflows\jobs\toolchain\steps\check-swift.cmd

  sdk:

    runs-on: windows-latest
    needs: [curl, icu, libxml2, toolchain, zlib]
    strategy:
      matrix:
        branch: ['master']
        include:
          - branch: 'master'
            libdispatch-ref: 'master'
            foundation-ref: 'master'
            xctest-ref: 'master'

          - branch: '5.2'
            libdispatch-ref: 'swift-5.2-branch'
            foundation-ref: 'swift-5.2-branch'
            xctest-ref: 'swift-5.2-branch'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Checkout Info
        uses: actions/download-artifact@v1
        with:
          name: checkout-${{ matrix.branch }}
          path: 'a/checkout'
      - name: Read Checkout Info
        shell: cmd
        run: |
          set /p SW_LLVM_REV=< a\checkout\llvm-project.txt
          set /p SW_SWIFT_REV=< a\checkout\swift.txt
          
          echo llvm-project rev is %SW_LLVM_REV%
          echo swift rev is %SW_SWIFT_REV%
          
          echo ::set-env name=SW_LLVM_REV::%SW_LLVM_REV%
          echo ::set-env name=SW_SWIFT_REV::%SW_SWIFT_REV%
          
      - name: Configure Git
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-git.cmd

      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: ${{ env.SW_LLVM_REV }}
          fetch-depth: 1
          path: 's/llvm-project'
      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: ${{ env.SW_SWIFT_REV }}
          fetch-depth: 1
          path: 's/swift'
      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: ${{ matrix.libdispatch-ref }}
          fetch-depth: 1
          path: 's/swift-corelibs-libdispatch'
      - name: Checkout foundation
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-foundation'
          ref: ${{ matrix.foundation-ref }}
          fetch-depth: 1
          path: 's/swift-corelibs-foundation'
      - name: Checkout xctest
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-xctest'
          ref: ${{ matrix.xctest-ref }}
          fetch-depth: 1
          path: 's/swift-corelibs-xctest'

      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: 'a'
      - name: Download curl
        uses: actions/download-artifact@v1
        with:
          name: curl
          path: 'a'
      - name: Download libxml2
        uses: actions/download-artifact@v1
        with:
          name: libxml2
          path: 'a'
      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: 'a'
      - name: Download toolchain
        uses: actions/download-artifact@v1
        with:
          name: toolchain-${{ matrix.branch }}
          path: 'a'

      - name: Configure Build Environment
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-build-environment.cmd

      - name: Use Python 2.7.x
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 2.7.x

      - name: Configure LLVM
        shell: cmd
        run:  scripts\workflows\jobs\sdk\steps\configure-llvm.cmd

      - name: Configure Swift Standard Library
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-swift-stdlib.cmd

      - name: Build Swift Standard Library
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-swift-stdlib.cmd

      - name: Configure libdispatch
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-libdispatch.cmd

      - name: Build libdispatch
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-libdispatch.cmd

      - name: Configure Foundation
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-foundation.cmd

      - name: Build Foundation
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-foundation.cmd

      - name: Configure XCTest
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-xctest.cmd

      - name: Build XCTest
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-xctest.cmd

      - name: Install Swift Standard Library
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\install-swift-stdlib.cmd

      - name: Install Foundation
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\install-foundation.cmd

      - name: Install XCTest
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\install-xctest.cmd

      - name: Install libdispatch
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\install-libdispatch.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: sdk-${{ matrix.branch }}
          path: i

      - name: Configure libdispatch Tests
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-libdispatch-tests.cmd

      - name: Build libdispatch Tests
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-libdispatch.cmd

      - name: Test libdispatch
        shell: cmd
        continue-on-error: true
        run: scripts\workflows\jobs\sdk\steps\test-libdispatch.cmd

      - name: Configure Foundation Test Environment
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-foundation-test-environment.cmd

      - name: Configure Foundation Tests
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\configure-foundation-tests.cmd

      - name: Build Foundation Tests
        shell: cmd
        run: scripts\workflows\jobs\sdk\steps\build-foundation.cmd

      - name: Test Foundation
        shell: cmd
        continue-on-error: true
        run: scripts\workflows\jobs\sdk\steps\test-foundation.cmd
