name: swift-build-script
on:
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  swift:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [main, 5.4, 5.3]
        spec: [apple, readdle]
        include:
          - spec: apple
            enable-no-objc-patch: NO
            stdlib-patch-enabled: NO
          - spec: readdle
            enable-no-objc-patch: YES
            stdlib-patch-enabled: YES
          - branch: main
            python-version: 3.7.x
          - branch: 5.4
            python-version: 3.7.x
          - branch: 5.3
            python-version: 2.7.x

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get CMake 3.19.2
        uses: lukka/get-cmake@v3.19.2

      - name: Install VS 16.9
        if: matrix.branch == 5.3
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --add Microsoft.VisualStudio.Component.VC.14.28.16.9.x86.x64 --add Microsoft.VisualStudio.Component.VC.14.28.16.9.ATL --quiet --norestart

      - name: Prepare Build Drive
        run: |
          call scripts\tools\get-free-drive.cmd
          subst %SW_FREE_DRIVE% ${{ github.workspace }}
          echo SW_WORK_DIR=%SW_FREE_DRIVE%>>%GITHUB_ENV%

      - name: Configure
        run: |
          subst

          scripts\configure.cmd^
           --interactive=NO^
           --branch ${{ matrix.branch }}^
           --sources-dir %SW_WORK_DIR%\s^
           --build-dir %SW_WORK_DIR%\b^
           --install-dir %SW_WORK_DIR%\i^
           --skip-toolchain-swift-test=YES^
           --skip-sdk-dispatch-test=YES^
           --skip-sdk-foundation-test=YES^
           --enable-no-objc-patch=${{ matrix.enable-no-objc-patch}}^
           --enable-print-patch=${{ matrix.stdlib-patch-enabled }}

      - name: Build
        run: |
          if "${{ matrix.branch }}"=="5.3" set SW_VC_VERSION=14.28.29910
          scripts\build.cmd

      - name: Remove Build Drive
        if: always()
        run: subst /d %SW_WORK_DIR%
