name: swift-snapshot-trigger

on:
  workflow_dispatch:

jobs:
  
  trigger-snapshot:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        spec: ['main', '5.4', '5.3']

    steps:
      - name: Print Event Data
        run: echo ${{ toJson(github) }}

      - name: Trigger `${{ matrix.spec }}` Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/actions/workflows/{workflow_id}/dispatches
          repository: ${{ github.repository }}
          workflow_id: swift-snapshot.yml
          ref: ${{ github.ref }}
          inputs: '{ "branch-spec": "${{ matrix.spec }}" }'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
